[tool.poetry]
name = "makenew-serverless-python"
version = "3.0.6"
description = "Package skeleton for a Python Serverless project on AWS Lambda."
authors = ["Evan Sosenko <razorx@evansosenko.com>"]
license = "MIT"
readme = "README.rst"
homepage = "https://github.com/makenew/serverless-python"
repository = "https://github.com/makenew/serverless-python"
include = ['poetry.lock']

[tool.poetry.dependencies]
python = "~3.8.6"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
bump2version = "^1.0.0"
pylint = "^2.4"
pytest = "^6.1"
pytest-cov = "^2.8"
pytest-incremental = "^0.5.0"
pytest-runner = "^5.2"
pytest-watch = "^4.2"
twine = "^3.0"

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"

[tool.pytest.ini_options]
norecursedirs = [
    "node_modules"
]
